#!/bin/bash -e

. config.conf

NDK_PATH=$(pwd)"/${NDK_DIR_NAME}"
SDK_TOOLS_PATH=$(pwd)"/${SDK_DIR_NAME}/tools"
OPENH264_PATH=$(pwd)"/${OPENH264_DIR_NAME}"
LIB_PATH="${OPENH264_BUILD_OUT_PATH}/libs"
LOG_PATH="${OPENH264_BUILD_OUT_PATH}/logs"
TMP_DIR="/tmp/openh264"

export PATH=${SDK_TOOLS_PATH}:$PATH

rm -rf "${OPENH264_BUILD_OUT_PATH}"
mkdir -p "${LIB_PATH}"
mkdir -p "${LOG_PATH}"

for arch in "${TARGET_ARCHS[@]}"
do
    echo "Building OpenH264 for target arch $arch ..."
    rm -rf "${TMP_DIR}"
    mkdir -p "${TMP_DIR}"
    cd ${OPENH264_PATH}
    cp -r * ${TMP_DIR}
    cd ${TMP_DIR}
    mkdir -p "${LIB_PATH}/${arch}"
    
    #change default output DIR for make install
    sed -i "s*PREFIX=/usr/local*PREFIX=${LIB_PATH}/${arch}*g" Makefile
    
    ARGS="OS=android NDKROOT=${NDK_PATH} NDKLEVEL=${OPENH264_TARGET_NDK_LEVEL} "
    ARGS="${ARGS}TARGET=android-${TARGET_ANDROID_API} ARCH="
    
    if [ "$arch" == "armeabi" ]
    then
        ARGS="${ARGS}arm APP_ABI=armeabi"

    elif [ "$arch" == "armeabi-v7a" ]
    then
        ARGS="${ARGS}arm"

    elif [ "$arch" == "x86" ]
    then
        ARGS="${ARGS}x86"

    elif [ "$arch" == "x86_64" ]
    then
        ARGS="${ARGS}x86_64"

    elif [ "$arch" == "arm64-v8a" ]
    then
        ARGS="${ARGS}arm64"

    elif [ "$arch" == "mips" ]
    then
        ARGS="${ARGS}mips"

    elif [ "$arch" == "mips64" ]
    then
        ARGS="${ARGS}mips64"
    fi
    
    make ${ARGS} >>"${LOG_PATH}/${arch}.log" 2>&1
    mkdir -p ${LIB_PATH}/${arch}
    make ${ARGS} install >>"${LOG_PATH}/${arch}.log" 2>&1
done

echo "Finished building OpenH264! Check output folder: ${OPENH264_BUILD_OUT_PATH}"

